runtime: python310

instance_class: F2
entrypoint: gunicorn -b :$PORT host.server:app

inbound_services:
- warmup

automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /
  script: host.server
  secure: always

- url: /static
  static_dir: host/static
  secure: always